resource_group = "tannu-rg"
Region = "Canada Central"
availability_zones = ["2", "3"]
aks_name = "my-aks"
aks_version = "2.0"
node_count = "-1"
cluster_type = "Private"
vm_name = "tannnu"
vm_pass = "asdfghhj"
